// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Square$ReactTemplate = require("./Square.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Square$ReactTemplate.make(/* array */[])), "square");

/*  Not a pure module */
