// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Grid$ReactTemplate = require("./Grid.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Grid$ReactTemplate.make(/* array */[
              "green",
              "pink",
              "blue",
              "pink",
              "pink",
              "pink"
            ], /* array */[])), "square");

/*  Not a pure module */
