/* Untyped file generated by genType. */

import Synth from './Synth';

import * as React from 'react';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function (children) { return ReasonReact.wrapJsForReason(Synth, {}, children); };
